### ISSUE TITLE
Engine battle 

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#501]
It would be nice to have **engines tournament battle** option.

**Comment by czbar** [comment]
Now that I have refactored out the "Play against computer" mode (it was tightly bound to the Study Tree, originally), I am looking again at this old request.

What exactly did you mean here?  An engine playing against itself or 2 different engines playing against each other.

If the former, then it would be relatively easy to implement now. And I can see that it may be helpful for users to see how the game could potentially develop from a given position. Especially, that I allow the user to manipulate engine's "accuracy".

If the latter (as the wording of your request seems to suggest) then it is considerably harder but, more importantly, it doesn't fit the purpose of Chess Forge, in my opinion.  The program's goal is to help humans to improve rather than to compare the strength of the engines.

**Comment by akaKarthick** [comment]
actually i meant 2 different engines playing against each other. If it doesn't fit the purpose of Chess Forge, we'll close this issue. This is my first issue. I opened github account for chessforge. and raised this issue. at that time i dont know anything about github and chessforge.
