### ISSUE TITLE
Show the next move instead of the previous move in Find identical position's result.

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#558]
![Screenshot (107)](https://user-images.githubusercontent.com/125844120/228533873-485a9c71-ef21-4c57-8b3a-254a1b63eeb2.png)

I know very well that d5 is played here. 

So it would be nice to show the next move instead of the previous move.

**Comment by czbar** [comment]
Thanks for the suggestion. Also, please see issue #522 https://github.com/czbar/ChessForge/issues/522 for our current thinking on how to improve this feature.  The original need arose because we were working on opening studies where same positions where arrived after transpositions.  So, there were not necessarily the same "previous" moves.  Hence, we need to somehow address all different cases in a satisfactory manner.

**Comment by czbar** [comment]
This has now been completely refactored and will be available when the next build is published (0.9.9). See https://github.com/czbar/ChessForge/wiki/Identical-Positions
