### ISSUE TITLE
pieces movements and notation in Intro 

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#562]
bug?

https://user-images.githubusercontent.com/125844120/229349564-c51c697b-0ea2-4798-b288-5593f8eee2ea.mp4

**Comment by czbar** [comment]
No, this is by design.  The Intro tab is meant for free, book-like text illustrated with moves and diagrams.  The ability to move pieces around while in this tab is only there to help with editing, not to check validity of those moves or positions. Similarly, you can insert diagrams with any positions whatsoever. The legality of the positions is not checked (unlike when creating positions for exercises, where it is).  So, you can have 10 queens and no kings, or whatever. You can enter 1.e4 1.d4 1.c4 next to each etc etc. An early request for this tab is here https://github.com/czbar/ChessForge/issues/427 although things have evolved since.
