### ISSUE TITLE
Floating Chess Boards: A Convenient Way to View Game History and Exercise Positions

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#605]
If the chapter area has a lot of games and exercises, it would be nice if the final move of the game or the position of the exercise was displayed as a floating board when hovering with the cursor. just like training mode in chessforge. also like chess.com

![Screenshot (205)](https://github.com/czbar/ChessForge/assets/125844120/3008047c-1b46-4871-8c0f-38ba32056aa5)
![Screenshot (206)](https://github.com/czbar/ChessForge/assets/125844120/809511f0-27a0-4722-8469-e319c4ab2353)
![Screenshot (207)](https://github.com/czbar/ChessForge/assets/125844120/841bb925-ea57-48fc-9432-207fe95291ca)

**Comment by czbar** [comment]
Can be done, of course. 

Btw note that the main chessboard already shows the final position of the highlighted game (or the **initial** position of the highlighted study - since we don't want to expose the solution :)).

But I guess a floating board would enhance that functionality since it does not require clicking on the line.  Still, for exercises I would show the **initial** position.

**Comment by akaKarthick** [comment]
But it is the fastest way to find the game by ending position. 

Isn't it annoying to click and search one by one? 

Here is my situation.

I am teaching my niece to play chess. I trying to convert all 3000 games from my old chess.com account into a single pgn file.  

After that I will train her. 

When the game is over in many ways. 

blunder a piece and resign, out of time, internet disconnect, middle game mate in 1, forced draw by 3 fold rep, forced capture and stalemate, proper endgame fight and checkmate. 


I know it is hard to filter the game. But at least I can do it faster by "floating board" in the ending position. Comparatively clicking one by one..

But it's completely your decision to implement.

**Comment by czbar** [comment]
Fair enough. It is quite easy to implement so I'll do it.

**Comment by czbar** [comment]
Implemented. "Private" version 1.1.1 available here https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

![image](https://github.com/czbar/ChessForge/assets/7270924/0b5052b3-c613-49f5-b0e8-498189e7b840)

**Comment by akaKarthick** [comment]
Chapter layout enhancement.

Is this possible? If you are interested, we can reopen this issue.

![Screenshot (242)](https://github.com/czbar/ChessForge/assets/125844120/fc912483-f0c6-4d41-8373-2e634016dc76)
![Screenshot (241)](https://github.com/czbar/ChessForge/assets/125844120/cd655c17-cb38-4abf-96e2-afdbd180ca55)

**Comment by czbar** [comment]
Can you elaborate, please? Where on the screen would you like to have that list of games and, more importantly, how would they be selected/filtered?

**Comment by akaKarthick** [comment]
![Screenshot (247)](https://github.com/czbar/ChessForge/assets/125844120/e251d74d-e725-4140-b8fa-c56598798aeb)
fig:1

The home page would be a bit nicer if it displayed games like this(fig:1) instead of showing them like this(fig:2).


![Screenshot (246)](https://github.com/czbar/ChessForge/assets/125844120/98412686-28b1-4f36-aa59-9ee308d9b756)
fig:2

Or at least it would be better to show it like this. It also has a lot of unnecessary filters.
![Screenshot (249)](https://github.com/czbar/ChessForge/assets/125844120/0bd25544-af3e-4269-93d0-ec6c87f5f705)

**Comment by czbar** [comment]
Oh, ok, I understand. It would indeed look nicer. 

This would require a separate table for each chapter, though.  The chapters' titles would go in between those tables. Currently it is all just lines of text.  

Such a change is possible but not trivial. Let's consider this once all the other outstanding issues, and functionality, have been sorted out.  Feel free to open a new issue (rather than re-opening this one), if you wish.
