### ISSUE TITLE
Replay

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#645]
https://youtu.be/1lLZjPTNMFw

I dont know how to describe this bug?

I mean scoresheet & moves after switching game.

**Comment by akaKarthick** [comment]
still the last moving piece is moving in next game.

**Comment by czbar** [comment]
Yes, this is a more generic issue in that it happens in replay in all contexts. The last move's animation always runs to conclusion.

I have opened a new bug #647 for this and will close this one as the main issue has been fixed. 

(Well, not quite.  I am not closing yet because I just noticed that the replay continues if we switch to a bookmarks or chapters tab. Will fix that in the next build.)

**Comment by akaKarthick** [comment]
Ok reopen if you want. and close it when its done. 👍🏻
