### ISSUE TITLE
Sometimes Engine not making move in Training session, Exercise (initial position)

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#651]

**Comment by czbar** [comment]
Do you have some more info for this? When you say "_Exercise (initial position)_" I understand that the problem occurs when you start training from the initial position of the exercise, right?  And "_Engine not making move_" means that the **game has started** (i.e. we are out of the workbook)? Or is it the program not making a move that is **still in the workbook (exercise)**?

**Comment by czbar** [comment]
I have identified and found some issues that were occurring in the Training mode when continuous evaluation was on.  Not sure if it will address the issues, you have encountered but it will be worth to re-test. Implemented in the private build 1.2.3 that I intend to publish in a couple of days.

**Comment by akaKarthick** [comment]
oh sorry. I was busy. 
Here is the demo. is it enough? 

https://youtu.be/9GDAaUGhhmE  

i also dont know why?

**Comment by akaKarthick** [comment]
> Do you have some more info for this? When you say "_Exercise (initial position)_" I understand that the problem occurs when you start training from the initial position of the exercise, right? And "_Engine not making move_" means that the **game has started** (i.e. we are out of the workbook)? Or is it the program not making a move that is **still in the workbook (exercise)**?

Still in the workbook

**Comment by czbar** [comment]
No problem, I realize you have other things to do too :)  By the way, I really appreciate the time you have put into submitting comments/reports/suggestions that have made the program better and much less buggy.   

As for the issue at hand, looking at the video, that behavior is by design. 

My thinking was as follows: when the solution is hidden (for example, after exiting the solving mode) and the user tries to move a piece on the main board, the program does not know what the user's intention is.  Do they want to start solving, but did not click any of the solution buttons, or do they want to edit the solution? Hence the message/question to the user to clarify their intention.

Of course, I can change this behavior if we can think of a better logic there.

**Comment by akaKarthick** [comment]
I guess you missed it. I meant the difference between 7th second and 21 st second.

**Comment by czbar** [comment]
Ah, ok. But in the 7th second "**Solving is in progress...**" so the move is allowed, while in the 21st second there is no active solving mode, and the move is blocked as per the logic I described above.     

Does this explain or am I missing something still?

**Comment by akaKarthick** [comment]
Yes. You missed it. Engine not on responding first try.

https://youtu.be/hbrJuqNARSM

**Comment by czbar** [comment]
Oh, now I got it. Thanks!

**Comment by akaKarthick** [comment]
Did you noticed the Speed in exercise ?

https://youtu.be/EY6lCbQ9sH8

**Comment by czbar** [comment]
Only that it's fast in both Solving and Training modes :).  What specifically should I have noticed?

**Comment by akaKarthick** [comment]
No. I feel very slow in exercise.  I didnt mean engines reply moves. I mean my piece placements is very slow in exercise.

I request you to watch this clip in 0.5x.

**Comment by czbar** [comment]
Yes, that I have noticed, I'll be looking at this as soon as I start addressing various performance issues.

**Comment by czbar** [comment]
Actually, I had my suspicion, and I have already resolved the slowness issue. I'll try to publish a new private build 1.2.3 tonight (Costa Rican time :))

Explanation: a while back I added a function checking for identical positions within the Workbook when you make a move. In a large Workbook like your "SyZyGy" that takes a very long time.

My implementation has multiple issues: one, it shouldn't run in the Solving mode to start with, two, more importantly, it should run as a background process which is what I will implement as part of the planned performance improvements. For now, temporarily, I commented out that function altogether.  

(I still can't reproduce the program not responding to the first move in the exercise, though. So, it may not be fixed in tonight's build.)

**Comment by czbar** [comment]
I have published a new private build 1.2.3 at the usual location https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

As I mentioned above, I haven't fixed the original issue as I can't reproduce it.  Can you reliably reproduce it on your machine?  Does it only happen on the first solving attempt and then works correctly every time after that?

**Comment by czbar** [comment]
Ok, disregard my questions. My wife was just able to reproduce this issue on her laptop. So, I have something to work with.

**Comment by akaKarthick** [comment]
Now fixed.

**Comment by akaKarthick** [comment]
> Explanation: a while back I added a function checking for identical positions within the Workbook when you make a move. In a large Workbook like your "SyZyGy" that takes a very long time.
> 


You are talking about 4000+ exercise. 
Me imported 

![Screenshot (380)](https://github.com/czbar/ChessForge/assets/125844120/499c9d63-e02f-4c77-811a-79a12a9c1bb9)


![image](https://github.com/czbar/ChessForge/assets/125844120/b8d66ac8-6715-459a-8789-52a0e1a02c63)

**Comment by czbar** [comment]
> Now fixed.

I think it still may happen somewhere, sometimes  (looks like some timing issue with Windows messaging). But I can't repro on my machine, and on my wife's machine only happens with the non-debug build so very hard to investigate.

**Comment by czbar** [comment]
Just FYI. We were able to force a repro (with the previous version) and I have identified the reason for the problem.  It's truly fixed now.
