### ISSUE TITLE
Show last and initial position of the game

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#664]
I would like to request a new feature that would allow users to show the last and initial position of a game by pressing the down and up arrow keys, respectively. This would be a helpful feature for players who want to review their games or analyze their mistakes.

**Comment by czbar** [comment]
Show or navigate to? In the Game view you can navigate to the start and end by pressing Home and End keys respectively. 

Or do you mean something else?

**Comment by akaKarthick** [comment]
Navigate. I'm not good in English

**Comment by czbar** [comment]
So, is the current functionality (Home and End buttons) sufficient?

**Comment by akaKarthick** [comment]
I never used home and end btn. But in chess.com and lichess have this feature.

**Comment by czbar** [comment]
You can use SHIFT-UP/DOWN arrows instead of HOME/END, if you prefer.  The only difference is that SHIFT-UP arrow takes you to the first move, while HOME takes you to the starting position.

I have reserved the UP/DOWN arrows for switching lines when you are at a fork.  If you are at a position with multiple possible continuation, pressing the arrows allows you to rotate through the options (changing lines).

**Comment by akaKarthick** [comment]
Agree

**Comment by czbar** [comment]
Your question prompted me to change the text in the "Hint Box" under the main chessboard to list the main navigational keyboard  shortcuts.  Especially up/down arrows at a fork, as this is unique to Chess Forge, I believe.
