### ISSUE TITLE
Promotion popup showing in unusual place

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#717]
When promoting a pawn, the promotion popup appears in an unusual place on the screen. which makes it difficult to select the desired promotion piece.

**Comment by akaKarthick** [comment]
![2023-09-20-16-01-05-841.jpg](https://github.com/czbar/ChessForge/assets/125844120/1c3fa22f-89ce-49c2-a26a-83d1622ae49f)

![2023-09-20-16-04-37-135.jpg](https://github.com/czbar/ChessForge/assets/125844120/af2f15cc-3b79-4a87-a64a-2b9442c0f807)

![2023-09-20-16-04-11-351.jpg](https://github.com/czbar/ChessForge/assets/125844120/3231b3a8-6c29-4e32-a0ac-f8de6b40ceb5)

**Comment by czbar** [comment]
Forgot about this...  Yeah, I will need to completely refactor the implementation of the promotion dialog.  Currently, the placement calculation and the sizing only works in some circumstances.  Instead of being a dialog, like it is now, I will make it an internal image in the chessboard where it will be easy to position and scale.

**Comment by czbar** [comment]
Fixed in 1.3.4 https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
