### ISSUE TITLE
Cursor freezes after clicking scoresheet titles in Play against Engine and Training modes

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#751]
**Steps to reproduce:**

- Select any position from any game.

- Click the "Play against Engine" or "Training" .

- Click any of the scoresheet titles: "#", "White", or "Black".

- Attempt to move a piece.

![Screenshot (7)](https://github.com/czbar/ChessForge/assets/125844120/793667e5-f34d-4087-b395-fe044e335599)

The user should be able to move a piece after clicking on a scoresheet title.

**Actual behavior:**

The cursor freezes and the user is unable to move a piece.

**Comment by czbar** [comment]
Wow, that's another gem! :(  This is something internal to the Microsoft's Data Grid control but I am not sure why it is happening here nad not in the Study or Games view(?). 

Anyway, fixed in 1.3.6. (I am now intercepting mouse clicks on the header, not allowing the DataGrid to apply the default handling).
