### ISSUE TITLE
Misinterpreted comments-variation combo from chess.com

### ISSUE THREAD

**Issue by pzsapa** [czbar/ChessForge#780]
I guess the comment-variation combo is misinterpreted in a special case. The chess.com created this:
```
9. h4 h6 {INACCURACY (+0.81)} ({(-0.52) The best move was} 9... Nbd7 10.
Bb5 c5 11. O-O Ng4 12. Bxd7 Qxd7 13. Re1 Rae8 14. Ne5 Nxe5 15. dxe5 f6 16. exf6
Rxf6 17. f4) 10. 
```
and it is shown in the games section something like this:
```
9. h4 [(-0.52) The best move was] h6 [(+0.81) The best move was]
  9... Nbd7 10. Bb5 c5 11. O-O Ng4 12. Bxd7 Qxd7 13. Re1 Rae8 14. Ne5 Nxe5 15. dxe5 f6 16. exf6
Rxf6 17. f4) 
10.
```
I attached the PGN file as TXT and a screenshot from ChessForge. 
CF version: 1.4.2.0

[Komodo10_vs_pzsapa_2023.11.22.txt](https://github.com/czbar/ChessForge/files/13440497/Komodo10_vs_pzsapa_2023.11.22.txt)
![CF_Komodo10_vs_pzsapa_2023 11 22](https://github.com/czbar/ChessForge/assets/23297840/c427bd43-2140-4e82-bab6-82f5a3ff7523)

**Comment by czbar** [comment]
Thank you for submitting this issue. Indeed, Chess Forge's parser gets
confused when a comment follows branching to a sub-variation i.e. when "{"
follows "(". In other words, it does not handle comments *before* move.

I'll fix this in 2 stages. First, I will make sure that such pgns are
correctly parsed except for the "before-move" comments that will be dropped
(which is what lichess seems to be doing when you upload this pgn via a
study). And second, I'll add support for the before-move comments. (The
latter requires some update to the GUI so that the user can enter such
comments too.)
