### ISSUE TITLE
Problem copying games from external program

### ISSUE THREAD

**Issue by SanAndTang** [czbar/ChessForge#792]
Sometimes I try to copy a variation from Chessable and it does not copy.
     Example from Chessable (exclude quotes) :  "1.e4 e5 2.Nf3 Nf6 3.Nc3 Bc5 4.Nxe5 Nc6 5.Nxc6 dxc6 6.h3 "
There is no problem to copy a game or part of a game from Chessforge to a text editor but it does not copy from the txt editor to Chessforge.

Is it only me or the correct Chessforge behavior?

I am using version 1.5.0.0 on Windows 11

**Comment by SanAndTang** [comment]
By the way, I love Chessforge and use it all the time. Keep developping.

**Comment by czbar** [comment]
Thank you for opening this issue and I'm glad that you find ChessForge useful.

Pasting plain text chess notation from the clipboard has not been implemented yet, so currently this is expected behavior. However, now that you have raised it, we will prioritize addressing this issue. Shouldn't take too long to implement.

**Comment by czbar** [comment]
Published in version 1.5.1 (updated on the download side https://sourceforge.net/projects/chessforge/)

**Comment by eradecka** [comment]
Tested copying the text from an editor and works fine. Closing the issue.
