### ISSUE TITLE
Unintended Promotion Due to Popup Bounding Box Issue

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#796]
I'm writing to report a bug I've encountered that interferes with the promotion process. Here's a detailed description:

**Steps to Reproduce:**
Move a pawn to the last rank, triggering the promotion piece selection popup.
Decide to cancel the promotion and click outside the popup, ideally on an empty square.

**Expected Behavior:**
The promotion popup should disappear, and the pawn should remain unpromoted.

**Actual Behavior:**
If the click falls within a few pixels around the popup's edges, the pawn is promoted to a queen, even though the selection was not intentional.

**Potential Cause:**
The popup's bounding box seems to extend slightly beyond its visible boundaries, inadvertently capturing clicks that were intended to cancel the promotion.
Impact:

This bug can lead to unintended promotions, potentially affecting game outcomes and causing frustration for users.

**Request:**
Please investigate and address this bug to ensure accurate promotion mechanics and a smoother user experience. I'm happy to provide further details or assist with testing if needed.

https://youtu.be/icVQDtmk4Qo

Thank you for your attention to this matter.

**Comment by czbar** [comment]
Good find.  The whole "bounding box" is shifted by 20 pixels to the right because the click point was incorrectly calculated relative to the chessboard image rather than the whole area that includes the boundary (the one with numbers 1-8). The fix is trivial so it will appear in the next release.

While looking at it, I also found an unrelated problem with the vertical checks there.  It will be fixed as well, of course.  Thanks!

**Comment by czbar** [comment]
Fixed in version 1.6.0
